export const countries = [
  { value: "AF", label: "Afeganistão" },
  { value: "ZA", label: "África do Sul" },
  { value: "AL", label: "Albânia" },
  { value: "DE", label: "Alemanha" },
  { value: "AD", label: "Andorra" },
  { value: "AO", label: "Angola" },
  { value: "AR", label: "Argentina" },
  { value: "AU", label: "Austrália" },
  { value: "AT", label: "Áustria" },
  { value: "BE", label: "Bélgica" },
  { value: "BO", label: "Bolívia" },
  { value: "BR", label: "Brasil" },
  { value: "CA", label: "Canadá" },
  { value: "CL", label: "Chile" },
  { value: "CN", label: "China" },
  { value: "CO", label: "Colômbia" },
  { value: "KR", label: "Coreia do Sul" },
  { value: "DK", label: "Dinamarca" },
  { value: "EC", label: "Equador" },
  { value: "ES", label: "Espanha" },
  { value: "US", label: "Estados Unidos" },
  { value: "FR", label: "França" },
  { value: "GR", label: "Grécia" },
  { value: "IN", label: "Índia" },
  { value: "IE", label: "Irlanda" },
  { value: "IS", label: "Islândia" },
  { value: "IL", label: "Israel" },
  { value: "IT", label: "Itália" },
  { value: "JP", label: "Japão" },
  { value: "LU", label: "Luxemburgo" },
  { value: "MX", label: "México" },
  { value: "NO", label: "Noruega" },
  { value: "NZ", label: "Nova Zelândia" },
  { value: "NL", label: "Países Baixos" },
  { value: "PA", label: "Panamá" },
  { value: "PE", label: "Peru" },
  { value: "PT", label: "Portugal" },
  { value: "GB", label: "Reino Unido" },
  { value: "RU", label: "Rússia" },
  { value: "SE", label: "Suécia" },
  { value: "CH", label: "Suíça" },
  { value: "UY", label: "Uruguai" },
  { value: "VE", label: "Venezuela" },
];
